AllCops:
  NewCops: enable

# Style
Style/StringLiterals:
  EnforcedStyle: single_quotes
Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always
Style/Documentation:
  Enabled: true
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
Style/AsciiComments:
  Enabled: false
Style/BisectedAttrAccessor:
  Enabled: true
Style/CaseLikeIf:
  Enabled: true
Style/ClassEqualityComparison:
  Enabled: true
Style/CollectionCompact:
  Enabled: true
Style/CombinableLoops:
  Enabled: true
Style/ConcatArrayLiterals:
  Enabled: true
Style/ConditionalAssignment:
  EnforcedStyle: assign_to_condition
Style/DirEmpty:
  Enabled: true
Style/DocumentDynamicEvalDefinition:
  Enabled: true
Style/EmptyMethod:
  EnforcedStyle: compact
Style/EmptyHeredoc:
  Enabled: true
Style/EndlessMethod:
  Enabled: true
  EnforcedStyle: disallow
Style/EnvHome:
  Enabled: true
Style/ExactRegexpMatch:
  Enabled: true
Style/FetchEnvVar:
  Enabled: true
Style/FileEmpty:
  Enabled: true
Style/FileRead:
  Enabled: true
Style/FileWrite:
  Enabled: true
Style/HashAsLastArrayItem:
  Enabled: true
Style/HashConversion:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashExcept:
  Enabled: true
Style/HashLikeCase:
  Enabled: true
Style/HashSyntax:
  EnforcedShorthandSyntax: always
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/IfWithBooleanLiteralBranches:
  Enabled: true
Style/InPatternThen:
  Enabled: true
Style/KeywordParametersOrder:
  Enabled: true
Style/MagicCommentFormat:
  Enabled: true
Style/MapCompactWithConditionalBlock:
  Enabled: true
Style/MapToHash:
  Enabled: true
Style/MapToSet:
  Enabled: true
Style/MinMaxComparison:
  Enabled: true
Style/NegatedIfElseCondition:
  Enabled: true
Style/NumberedParameters:
  Enabled: true
  EnforcedStyle: disallow
Style/OperatorMethodCall:
  Enabled: true
Style/QuotedSymbols:
  Enabled: true
Style/RedundantArgument:
  Enabled: true
Style/RedundantAssignment:
  Enabled: true
Style/RedundantDoubleSplatHashBraces:
  Enabled: true
Style/RedundantEach:
  Enabled: true
Style/RedundantFetchBlock:
  Enabled: true
Style/RedundantInitialize:
  Enabled: true
Style/RedundantSelfAssignment:
  Enabled: false
Style/RedundantSelfAssignmentBranch:
  Enabled: true
Style/RedundantStringEscape:
  Enabled: true
Style/ReturnNilInPredicateMethodDefinition:
  Enabled: true
Style/SoleNestedConditional:
  Enabled: true
Style/StringChars:
  Enabled: true
Style/StringConcatenation:
  Enabled: true
Style/SwapValues:
  Enabled: true
Style/YAMLFileRead:
  Enabled: true
Style/AmbiguousEndlessMethodDefinition:
  Enabled: true
Style/ArgumentsForwarding:
  Enabled: true
Style/ArrayIntersect:
  Enabled: true
Style/BitwisePredicate:
  Enabled: true
Style/CombinableDefined:
  Enabled: true
Style/ComparableClamp:
  Enabled: true
Style/DataInheritance:
  Enabled: true
Style/DigChain:
  Enabled: true
Style/FileNull:
  Enabled: true
Style/FileTouch:
  Enabled: true
Style/HashSlice:
  Enabled: true
Style/ItAssignment:
  Enabled: true
Style/KeywordArgumentsMerging:
  Enabled: true
Style/MapIntoArray:
  Enabled: true
Style/MultilineInPatternThen:
  Enabled: true
Style/NestedFileDirname:
  Enabled: true
Style/NilLambda:
  Enabled: true
Style/NumberedParametersLimit:
  Enabled: true
Style/ObjectThen:
  Enabled: true
Style/OpenStructUse:
  Enabled: true
Style/RedundantArrayConstructor:
  Enabled: true
Style/RedundantConstantBase:
  Enabled: true
Style/RedundantCurrentDirectoryInPath:
  Enabled: true
Style/RedundantFilterChain:
  Enabled: true
Style/RedundantFormat:
  Enabled: true
Style/RedundantHeredocDelimiterQuotes:
  Enabled: true
Style/RedundantInterpolationUnfreeze:
  Enabled: true
Style/RedundantLineContinuation:
  Enabled: true
Style/RedundantRegexpArgument:
  Enabled: true
Style/RedundantRegexpConstructor:
  Enabled: true
Style/SafeNavigationChainLength:
  Enabled: true
Style/SelectByRegexp:
  Enabled: true
Style/SendWithLiteralMethodName:
  Enabled: true
Style/SingleLineDoEndBlock:
  Enabled: true
Style/SuperArguments:
  Enabled: true
Style/SuperWithArgsParentheses:
  Enabled: true

# Metrics
Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CollectionLiteralLength:
  Enabled: true

# Layout
Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: no_space
Layout/EmptyLineAfterGuardClause:
  Enabled: true
Layout/LineLength:
  Max: 120
  Exclude:
    - 'Gemfile'
Layout/BeginEndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: start_of_line
Layout/CommentIndentation:
  Enabled: true
Layout/DotPosition:
  EnforcedStyle: leading
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/LineContinuationSpacing:
  Enabled: true
Layout/LineEndStringConcatenationIndentation:
  Enabled: true
  EnforcedStyle: indented
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Layout/SpaceBeforeBrackets:
  Enabled: true
Layout/LineContinuationLeadingSpace:
  Enabled: true

# Lint
Lint/AmbiguousAssignment:
  Enabled: true
Lint/AmbiguousOperatorPrecedence:
  Enabled: true
Lint/AmbiguousRange:
  Enabled: true
Lint/ArrayLiteralInRegexp:
  Enabled: true
Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true
Lint/ConstantDefinitionInBlock:
  Enabled: true
Lint/ConstantOverwrittenInRescue:
  Enabled: true
Lint/ConstantReassignment:
  Enabled: true
Lint/CopDirectiveSyntax:
  Enabled: true
Lint/DeprecatedConstants:
  Enabled: true
Lint/DeprecatedOpenSSLConstant:
  Enabled: false
Lint/DuplicateBranch:
  Enabled: true
Lint/DuplicateElsifCondition:
  Enabled: true
Lint/DuplicateMagicComment:
  Enabled: true
Lint/DuplicateMatchPattern:
  Enabled: true
Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true
Lint/DuplicateRequire:
  Enabled: true
Lint/DuplicateRescueException:
  Enabled: true
Lint/DuplicateSetElement:
  Enabled: true
Lint/EmptyBlock:
  Enabled: false
Lint/EmptyClass:
  Enabled: true
  AllowComments: true
Lint/EmptyConditionalBody:
  Enabled: true
Lint/EmptyFile:
  Enabled: true
Lint/EmptyInPattern:
  Enabled: true
  AllowComments: true
Lint/FloatComparison:
  Enabled: true
Lint/HashNewWithKeywordArgumentsAsDefault:
  Enabled: true
Lint/IdentityComparison:
  Enabled: true
Lint/IncompatibleIoSelectWithFiberScheduler:
  Enabled: true
Lint/ItWithoutArgumentsInBlock:
  Enabled: true
Lint/LambdaWithoutLiteralBlock:
  Enabled: true
Lint/LiteralAssignmentInCondition:
  Enabled: true
Lint/MissingSuper:
  Enabled: false
Lint/MixedCaseRange:
  Enabled: true
Lint/NoReturnInBeginEndBlocks:
  Enabled: true
Lint/NonAtomicFileOperation:
  Enabled: true
Lint/NumberedParameterAssignment:
  Enabled: true
Lint/NumericOperationWithConstantResult:
  Enabled: true
Lint/OrAssignmentToConstant:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/RedundantDirGlobSort:
  Enabled: true
Lint/RedundantRegexpQuantifiers:
  Enabled: true
Lint/RedundantSafeNavigation:
  Enabled: true
Lint/RedundantTypeConversion:
  Enabled: true
Lint/RefinementImportMethods:
  Enabled: true
Lint/RequireRangeParentheses:
  Enabled: true
Lint/RequireRelativeSelfPath:
  Enabled: true
Lint/SelfAssignment:
  Enabled: true
Lint/SharedMutableDefault:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Lint/SuppressedExceptionInNumberConversion:
  Enabled: true
Lint/SymbolConversion:
  Enabled: true
  EnforcedStyle: strict
Lint/ToEnumArguments:
  Enabled: true
Lint/TrailingCommaInAttributeDeclaration:
  Enabled: true
Lint/TripleQuotes:
  Enabled: true
Lint/UnescapedBracketInRegexp:
  Enabled: true
Lint/UnexpectedBlockArity:
  Enabled: true
Lint/UnmodifiedReduceAccumulator:
  Enabled: true
Lint/UnreachableLoop:
  Enabled: true
Lint/UselessConstantScoping:
  Enabled: true
Lint/UselessDefined:
  Enabled: true
Lint/UselessMethodDefinition:
  Enabled: true
Lint/UselessNumericOperation:
  Enabled: true
Lint/UselessRescue:
  Enabled: true
Lint/UselessRuby2Keywords:
  Enabled: true

# Bundler
Bundler/OrderedGems:
  Enabled: true

# Gemspec
Gemspec/AddRuntimeDependency:
  Enabled: true
Gemspec/DeprecatedAttributeAssignment:
  Enabled: false
Gemspec/DevelopmentDependencies:
  Enabled: false
Gemspec/RequireMFA:
  Enabled: false

# Naming
Naming/BlockForwarding:
  Enabled: true
  EnforcedStyle: explicit
Naming/PredicateName:
  Enabled: false

# Security
Security/CompoundHash:
  Enabled: true
Security/IoMethods:
  Enabled: true

Layout/HashAlignment:
  EnforcedColonStyle: key
  EnforcedHashRocketStyle: key

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Layout/ArgumentAlignment:
  EnforcedStyle: with_first_argument 

Layout/BlockAlignment:
  EnforcedStyleAlignWith: start_of_block  # or 'start_of_line' or 'either'

Layout/ArrayAlignment:
  EnforcedStyle: with_first_element

Layout/MultilineBlockLayout:
  Enabled: true

Layout/EndAlignment:
  EnforcedStyleAlignWith: keyword